services:
  app:
    image: roboguide-v1
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - PORT=9000
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - db
    # expose:
    #   - 9000
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  db:
    image: postgres
    restart: no
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - roboguideData:/var/lib/postgresql/data


volumes:
  roboguideData:
